# Generated by Django 2.2.16 on 2021-12-23 13:59

import apps.basics.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.basics.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.basics.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.basics.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.basics.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(default=str, max_length=100, verbose_name='接口名称')),
                ('url', models.CharField(default=str, max_length=200, verbose_name='请求url')),
                ('headers', models.TextField(blank=True, default=dict, null=True, verbose_name='请求头信息')),
                ('params', models.TextField(blank=True, default=dict, null=True, verbose_name='请求参数')),
                ('validators', models.TextField(blank=True, default=list, null=True, verbose_name='验证器')),
                ('extractors', models.TextField(blank=True, default=list, null=True, verbose_name='提取器')),
                ('desc', models.CharField(blank=True, default=str, max_length=200, null=True, verbose_name='接口描述')),
                ('last_exe_status', models.IntegerField(choices=[(0, '未执行'), (1, '成功'), (2, '失败'), (3, '阻塞'), (4, '部分失败')], default=0, verbose_name='最后执行状态')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '正常'), (2, '仅自己可见')], default=1, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '接口',
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.basics.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.basics.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.basics.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.basics.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(default=str, max_length=100, verbose_name='用例集名称')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '正常'), (2, '仅自己可见')], default=1, verbose_name='状态')),
                ('apis', models.ManyToManyField(to='api.Api', verbose_name='接口')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('dept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_suite_dept', to='permission.Dept', verbose_name='模块分类')),
            ],
            options={
                'verbose_name_plural': '接口集',
            },
        ),
    ]
