# Generated by Django 2.2.16 on 2022-01-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rpcitem_rpcrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpcitem',
            name='params',
            field=models.TextField(blank=True, default=str, null=True, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='rpcitem',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RpcItem'),
        ),
    ]
