# Generated by Django 2.2.16 on 2022-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220104_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpcitem',
            name='is_leaf',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否末结点'),
        ),
    ]
