# Generated by Django 2.2.16 on 2022-01-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220104_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpcrecord',
            name='item_ids',
        ),
        migrations.AddField(
            model_name='rpcrecord',
            name='items',
            field=models.ManyToManyField(default=0, to='api.RpcItem'),
        ),
        migrations.AlterField(
            model_name='rpcrecord',
            name='result',
            field=models.IntegerField(choices=[(0, '未执行'), (1, '成功'), (2, '失败'), (3, '阻塞'), (4, '部分失败')], default=0, verbose_name='执行状态'),
        ),
    ]
