# Generated by Django 2.2.16 on 2022-01-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220107_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpcrecord',
            name='items',
            field=models.TextField(default=dict, max_length=255, verbose_name='rpc方法'),
        ),
    ]
