# Generated by Django 2.2.16 on 2022-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220107_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpcrecord',
            name='items',
        ),
        migrations.AddField(
            model_name='rpcrecord',
            name='items',
            field=models.ManyToManyField(default=0, to='api.RpcItem', verbose_name='rpc方法'),
        ),
    ]
