# Generated by Django 2.2.16 on 2022-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220107_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpcitem',
            name='level',
            field=models.IntegerField(default=0, verbose_name='层级'),
        ),
    ]
