from apps.basics.system.models.celery_log import CeleryLog
from apps.basics.system.models.config_settings import ConfigSettings
from apps.basics.system.models.dict_data import DictData
from apps.basics.system.models.dict_details import DictDetails
from apps.basics.system.models.logininfor import LoginInfor
from apps.basics.system.models.message_push import MessagePush
from apps.basics.system.models.message_push import MessagePushUser
from apps.basics.system.models.operation_log import OperationLog
from apps.basics.system.models.save_file import SaveFile
